"""
Circuit Inspection Script for Quantum Chess Engine.

Builds and displays the ASCII representation of the Grover search
quantum circuit generated by Qiskit for move selection.
"""

from engine.board import Board
from engine.constants import Color, PieceType
from engine.piece import Piece
from engine.position import Position
from engine.state import GameState
from quantum.grover import GroverSearch


def main() -> None:
    # 1. Create a game state with white at (2,1) and black at (0,1)
    board = Board(size=3)
    board.place_piece(Position(2, 1), Piece(Color.WHITE, PieceType.PAWN))
    board.place_piece(Position(0, 1), Piece(Color.BLACK, PieceType.PAWN))
    state = GameState(board=board, current_turn=Color.WHITE)

    # 2. Build the Grover search circuit
    grover = GroverSearch()
    circuit = grover._build_grover_circuit(
        n_qubits=2, legal_indices=[0], n_iterations=1
    )

    # 3. Print quantum circuit summary and ASCII diagram
    print("=" * 60)
    print("  QUANTUM CHESS ENGINE — Qiskit Grover Circuit Inspection")
    print("=" * 60)
    print(f"Total Qubits:      {circuit.num_qubits}")
    print(f"Classical Bits:    {circuit.num_clbits}")
    print(f"Circuit Depth:     {circuit.depth()}")
    print(f"Gate Breakdown:    {circuit.count_ops()}")
    print("-" * 60)
    print("\nCircuit Diagram:\n")
    print(circuit.draw())
    print("-" * 60)


if __name__ == "__main__":
    main()
